version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            schema: public
            host: ec2-23-20-208-173.compute-1.amazonaws.com
            port: '5432'
            database: dutbfrh0ojpp7
            ssl: true
            user: tvxnqgfcyisudp
            password: a4ded629352610a0ce6b0d5b40662e5e5490bb01b00011e214ac7f8c69f7fc3d
            migrations: true
